### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ydeshayes** [fastrde/phonegap-downloader#6]
Hello !

When I try to install the plugin I get this error:

```
Notice: de.fastr.phonegap.plugins.md5chksum has been automatically converted to  cordova-plugin-fastrde-md5 and fetched from npm. This is due to our old plugins registry shutting down.
Fetching plugin " cordova-plugin-fastrde-md5" via npm
Failed to install 'de.fastr.phonegap.plugins.downloader':Error: Expected plugin to have ID " cordova-plugin-fastrde-md5" but got "cordova-plugin-fastrde-md5".
    at checkID (/Users/deshayesyann/.nvm/versions/node/v4.1.2/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:181:15)
    at /Users/deshayesyann/.nvm/versions/node/v4.1.2/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:166:9
    at _fulfilled (/Users/deshayesyann/.nvm/versions/node/v4.1.2/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/deshayesyann/.nvm/versions/node/v4.1.2/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/deshayesyann/.nvm/versions/node/v4.1.2/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/deshayesyann/.nvm/versions/node/v4.1.2/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/Users/deshayesyann/.nvm/versions/node/v4.1.2/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
Error: Expected plugin to have ID " cordova-plugin-fastrde-md5" but got "cordova-plugin-fastrde-md5".
```

Any idea ?

**Comment by fastrde** [comment]
There is a typo in the registry mapper. I sent a pull request to fix this.

**Comment by fastrde** [comment]
should be fixed
